---
blank_issues_enabled: false
contact_links:
  - name: NFT-Martkeplace-for-Artisan Community Support
    url: https://github.com/ThunderBolt-OS/NFT-Marketplace-for-Artisan/discussions
    about: Please ask and answer questions here.
